### ISSUE TITLE
VMs network DNS issues

### ISSUE THREAD

**Issue by elkoniu** [SSSD/sssd-test-suite#25]
After spawning new set of `master.client.vm`, `master.ipa.vm` and `master.ldap.vm` I cant ping ipa.vm from client.vm.
It looks like this is issue related to `systemd-resolved`. I checked and on my host (Fedora 33) `systemd-resolved` was enabled and running where on virtual machines it was deactivated. After I start `systemd-resolved` on all sssd-test-suite VMs machines started to see each other. I think the issue started when I updated from Fedora 31 to Fedora 33 or after latest updates on Fedora 33.

**Comment by pbrezina** [comment]
Fedora 33 has systemd-resolved enabled by default and it somehow conflicts with NetworkManager's dnsmasq config. This requires further investigation.

**Comment by elkoniu** [comment]
Workaround which works for me is to disable `systemd-resolved` on host:
1) `sudo systemctl disable systemd-resolved.service`
2) `sudo systemctl stop systemd-resolved`
3) Add `dns=default` in `[main]` section of `/etc/NetworkManager/NetworkManager.conf`
4) Delete symlink: `rm /etc/resolv.conf`
5) Restart NetworkManager: `sudo systemctl restart NetworkManager`

[https://gist.github.com/zoilomora/f7d264cefbb589f3f1b1fc2cea2c844c]

**Comment by justin-stephenson** [comment]
I had a similar issue solved by disabling systemd-resolved as stated here, the issue was evident based on the following command failing:
~~~
 ./sssd-test-suite provision enroll client ad 
...
<snip>
...
TASK [enroll-client : Join to Active Directory domain] ********************************************************************************************************
fatal: [client]: FAILED! => changed=true 
  cmd: |-                                                                      
    echo vagrant | realm join ad.vm || exit $?
    touch /etc/sssd/ad_enrolled || exit $?
  delta: '0:00:00.231752'                                                      
  end: '2021-07-13 12:55:58.664941'                                            
  msg: non-zero return code                                                    
  rc: 1                                                                        
  start: '2021-07-13 12:55:58.433189'                                          
  stderr: 'realm: No such realm found'                                         
  stderr_lines: <omitted>                                                      
  stdout: ''                                                                   
  stdout_lines: <omitted>    
~~~

**Comment by pbrezina** [comment]
We need to figure out how to make it work with resolved enabled.

**Comment by elkoniu** [comment]
@pbrezina Can we solve this easy by populating machines with some predefined `/etc/hosts` records? This way it may be independent from host DNS resolution. I was playing with Fedora 33 and Fedora 34 recently and even if I turn of systemd-resolved the `/etc/NetworkManager/dnsmasq.d/zone_vm.dnsmasq` zone is not always broadcasted the way VMs can see it. No mater if I am using F31, F32 or F32 VMs.

**Comment by elkoniu** [comment]
Closing as deprecated.
